# -*- coding: utf-8 -*-
"""hdd_and_cdd_noaa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nxOHbk1BFWZvL_TLXzSbOdxeAv3G_Ayj
"""

import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
regions = range(401,408)
hdd = pd.DataFrame({"Region": regions})
cdd = pd.DataFrame({"Region": regions})
cdd['type'] = np.repeat(np.array('cdd'), len(cdd))
hdd['type'] = np.repeat(np.array('hdd'), len(hdd))
for year in range(2010, 2025):
    hdd_filepath = f"/content/drive/MyDrive/ecodatalab/master/calcap/Energy/hdd_cdd/data/ClimateDivisions.Heating{year}.txt"
    hdd_year = pd.read_csv(hdd_filepath, sep="|", engine="python", skiprows=3, header=None)
    hdd_year = hdd_year.dropna(axis=1, how='all')
    hdd_year.columns = hdd_year.iloc[0]
    hdd_year = hdd_year[1:]
    hdd_year = hdd_year.rename(columns={hdd_year.columns[0]: "Region"}).reset_index(drop=True)
    hdd_year["Region"] = hdd_year["Region"].astype(int)
    date_cols = hdd_year.columns[1:]
    hdd_year[date_cols] = hdd_year[date_cols].apply(pd.to_numeric, errors='coerce')
    hdd_year = hdd_year[(hdd_year['Region'] > 400) & (hdd_year['Region'] < 408)].set_index("Region", inplace=False)
    total_hdd_year = []
    for region in regions:
        total_hdd_year.append(sum(hdd_year.loc[region]))
    hdd[year] = total_hdd_year

for year in range(2010, 2025):
    cdd_filepath = f"/content/drive/MyDrive/ecodatalab/master/calcap/Energy/hdd_cdd/data/ClimateDivisions.Cooling{year}.txt"
    cdd_year = pd.read_csv(cdd_filepath, sep="|", engine="python", skiprows=3, header=None)
    cdd_year = cdd_year.dropna(axis=1, how='all')
    cdd_year.columns = cdd_year.iloc[0]
    cdd_year = cdd_year[1:]
    cdd_year = cdd_year.rename(columns={cdd_year.columns[0]: "Region"}).reset_index(drop=True)
    cdd_year["Region"] = cdd_year["Region"].astype(int)
    date_cols = cdd_year.columns[1:]
    cdd_year[date_cols] = cdd_year[date_cols].apply(pd.to_numeric, errors='coerce')
    cdd_year = cdd_year[(cdd_year['Region'] > 400) & (cdd_year['Region'] < 408)].set_index("Region", inplace=False)
    total_cdd_year = []
    for region in regions:
        total_cdd_year.append(sum(cdd_year.loc[region]))
    cdd[year] = total_cdd_year

hdd_cdd_data = pd.concat([hdd,cdd])
hdd_cdd_data.to_csv("/content/drive/MyDrive/ecodatalab/master/calcap/Energy/hdd_cdd/results/hdd_cdd_data.csv", index=False)

