# -*- coding: utf-8 -*-
"""landfill_emissions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUAk3DcIEVPNf5bXf1sRRYhnC50WxuIg
"""

import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
final_output1 = pd.read_csv('/content/drive/MyDrive/ecodatalab/master/calcap/waste/waste_jun25/data/landfills - final_output.csv')
base_filter = final_output1[(final_output1['emissions_factor_source'] == 'facility_specific') & (final_output1['ghg_emissions'] > 0)]
emission_factor_array = []
for year in range(2010, 2020):
    one_col = []
    year_filter = base_filter[base_filter['year'] == year]
    one_col.append(np.sum(year_filter['ghg_emissions']) / np.sum(year_filter['waste_tons']))
    one_col.append(np.average(year_filter['used_emission_factor']))
    capped_filter = year_filter[year_filter['used_emission_factor'] < 50]
    one_col.append(np.sum(capped_filter['ghg_emissions']) / np.sum(year_filter['waste_tons']))
    one_col.append(np.average(capped_filter['used_emission_factor']))
    emission_factor_array.append(one_col)
emission_factor_df = pd.DataFrame(emission_factor_array, columns=[
    "emissions_per_waste",
    "avg_emission_factor",
    "emissions_per_waste_capped",
    "avg_emission_factor_capped"
], index=range(2010, 2020))
landfill_data = final_output1.copy()
for row in range(len(final_output1)):
    if landfill_data.loc[row, 'emissions_factor_source'] == 'statewide_average' or pd.isna(landfill_data.loc[row, 'ghg_emissions']) or landfill_data.loc[row, 'ghg_emissions'] == "":
        landfill_data.loc[row, 'used_emission_factor'] = emission_factor_df.loc[landfill_data.loc[row, 'year'], 'avg_emission_factor_capped']
        landfill_data.loc[row, 'emissions_factor_source'] = 'statewide_average'
        landfill_data.loc[row, 'ghg_emissions'] = landfill_data.loc[row, 'waste_tons'] * landfill_data.loc[row, 'used_emission_factor']
landfill_data.to_csv("/content/drive/MyDrive/ecodatalab/master/calcap/waste/waste_jun25/landfill_emissions.csv", index=False)